# Generated by Django 3.1.7 on 2021-03-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discusstheme',
            name='another_side',
            field=models.CharField(default='DUMMY', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discusstheme',
            name='one_side',
            field=models.CharField(default='DUMMY', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discusstheme',
            name='status',
            field=models.CharField(choices=[('o', 'Open'), ('a', 'Active'), ('c', 'Closed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='discusstheme',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
