# Generated by Django 3.1.7 on 2021-04-03 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discuss_app', '0003_auto_20210320_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discusstheme',
            name='another_side',
        ),
        migrations.RemoveField(
            model_name='discusstheme',
            name='another_side_count',
        ),
        migrations.RemoveField(
            model_name='discusstheme',
            name='max_n_of_member',
        ),
        migrations.RemoveField(
            model_name='discusstheme',
            name='one_side',
        ),
        migrations.RemoveField(
            model_name='discusstheme',
            name='one_side_count',
        ),
        migrations.CreateModel(
            name='DiscussSides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_n_of_member', models.IntegerField(default=5)),
                ('one_side', models.CharField(max_length=25)),
                ('one_side_count', models.IntegerField(default=0)),
                ('another_side', models.CharField(max_length=25)),
                ('another_side_count', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
                ('discuss_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discuss_app.discusstheme')),
            ],
        ),
    ]
