# Generated by Django 3.1.7 on 2021-04-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discuss_app', '0004_auto_20210403_0735'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscussSides',
            new_name='DiscussSide',
        ),
    ]
