# Generated by Django 3.1.7 on 2021-04-03 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discuss_app', '0006_auto_20210403_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2000, verbose_name='コメント')),
                ('discuss_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discuss_app.discussside')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discuss_app.user')),
            ],
        ),
    ]
