# Generated by Django 3.1.7 on 2021-04-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discuss_app', '0008_user_create_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='DiscussUser',
        ),
    ]
