# Generated by Django 3.1.7 on 2021-04-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discuss_app', '0009_auto_20210403_1710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscussUser',
            new_name='User',
        ),
    ]
